# Maki template version: 1.0

version: '3.2'

volumes:
  db-data:

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: .deploy/docker/nginx/Dockerfile
    volumes:
      - ./.deploy/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - 8081:80

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: .deploy/docker/php-fpm/Dockerfile
    env_file:
        - ./.env
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data

